fix (#1040): NPC objects to have unique server team names.
retrooper/packetevents pull request #1044
Opened 2024-10-28 18:00 UTC by ShreyasAyyengar

@retrooper!

2024-10-28 18:09 UTC, booky10 commented
Could you create a private field (type String) which defaults to this string for the teamname, plus a getter/setter?
That way you can decide wether to share prefixes/suffixes or not on your own, instead of being forced

2024-10-28 18:20 UTC, ShreyasAyyengar commented
> Could you create a private field (type String) which defaults to this string for the teamname, plus a getter/setter? That way you can decide wether to share prefixes/suffixes or not on your own, instead of being forced

Done!

2024-10-28 18:53 UTC, booky10 approved these changes
:+1:

2024-11-07 15:06 UTC, booky10 requested changes
Nevermind, this won't work
Please shorten the `teamName` to fit in the character limit of `16`

2024-11-07 16:49 UTC, ShreyasAyyengar commented
> Nevermind, this won't work Please shorten the `teamName` to fit in the character limit of `16`

Do team names have character limits? I thought that was just the NPC's name?

2024-11-07 21:48 UTC, booky10 commented
The team name limit was removed in 1.18, versions before that have a team name limit of 16

2024-11-10 18:13 UTC, ShreyasAyyengar commented
> The team name limit was removed in 1.18, versions before that have a team name limit of 16

I see. I've just committed to this fix; let me know if it's appropriate.

2024-11-11 08:49 UTC, booky10 commented
This won't solve the problem - the default team name will always consist of at least 18 characters

2024-11-11 20:48 UTC, ShreyasAyyengar commented
Would it be appropriate if the team name was simplified to just the entityId?

2024-11-11 22:39 UTC, booky10 commented
`npc_<id>` or so, yeah - it doesn't need to be complicated

2024-11-12 12:05 UTC, booky10 approved these changes

2024-11-13 20:54 UTC, retrooper requested changes

2024-11-13 20:54 UTC, retrooper commented on api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java
> +        if (PacketEvents.getAPI().getServerManager().getVersion().isOlderThan(ServerVersion.V_1_18)) {
Use
```java
serverVersion.isOlderThan(ServerVersion.V_1_18)
``` 
instead of accessing the global server version.

2024-11-13 23:44 UTC, ShreyasAyyengar commented on api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java
> +        if (PacketEvents.getAPI().getServerManager().getVersion().isOlderThan(ServerVersion.V_1_18)) {
Not quite sure what you mean here. I've written the check similarly to many other version-checking condition checks.

https://github.com/retrooper/packetevents/blob/d8a44fe8b6143578afd969c1eb192d782377e2b5/api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java#L260

https://github.com/retrooper/packetevents/blob/d8a44fe8b6143578afd969c1eb192d782377e2b5/api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java#L249

https://github.com/retrooper/packetevents/blob/d8a44fe8b6143578afd969c1eb192d782377e2b5/api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java#L233

2024-11-14 18:38 UTC, retrooper commented on api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java
> +        if (PacketEvents.getAPI().getServerManager().getVersion().isOlderThan(ServerVersion.V_1_18)) {
There's a variable within PacketWrapper, I'm saying use it.

2024-11-14 18:43 UTC, merged

2024-11-14 18:43 UTC, retrooper commented
Thanks for the PR.