2 new Wrappers
retrooper/packetevents pull request #353
Opened 2022-05-09 19:58 UTC by NoJokeFNA

With this pull request users can use two new wrappers (WrapperPlayClientCraftRecipeRequest & WrapperPlayServerCraftRecipeResponse) that work fine - I think there is nothing more to explain.
It was tested with the server versions: 1.8.8, 1.12.2, 1.13, 1.13.2, 1.14.4, 1.15.2, 1.16.5 and 1.18.2
Client-Versions: 1.18.2, 1.16.5, 1.13
Java-Versions: 8, 11, 16, 17

2022-05-09 20:01 UTC, retrooper requested changes
I'd say revert the debugs. Or atleast don't register the debug listener in the PacketEventsPlugin class. Otherwise looks fine to me.

2022-05-09 20:02 UTC, NoJokeFNA commented
Done!

2022-05-09 20:03 UTC, MWHunter requested changes

2022-05-09 20:03 UTC, MWHunter commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/client/WrapperPlayClientCraftRecipeRequest.java
> +    if (serverVersion.isNewerThanOrEquals(ServerVersion.V_1_12)) {
Did you mean specifically 1.12?

2022-05-09 20:09 UTC, retrooper commented
I didn't look into this too deply, but I'm not a fan of Objects in wrappers. It's an API.

2022-05-09 21:00 UTC, MWHunter approved these changes

2022-05-10 05:03 UTC, retrooper commented
Might merge this soon, but i wish it was possible to bring the recipe to one form without legacy and modern variables. I’ll see in a bit.

2022-06-22 12:59 UTC, merged