Update Declare Recipes packet and add packet for unlock recipes
retrooper/packetevents pull request #589
Opened 2023-06-07 00:32 UTC by BL19

It adds the packet for unlocking recipes and updates the packet for declaring recipes to contain the CraftingBookCategory.

2023-06-11 22:15 UTC, retrooper commented
Thank you for this PR. Will look into using this PR to complete the recipe wrappers and also update to 1.20.

2024-02-07 21:27 UTC, NoJokeFNA requested changes

2024-02-07 21:27 UTC, NoJokeFNA commented on api/src/main/java/com/github/retrooper/packetevents/protocol/recipe/data/ShapedRecipeData.java
> +    private CraftingBookCategory category;
```suggestion
    private final CraftingBookCategory category;
```

2024-02-07 21:27 UTC, NoJokeFNA commented on api/src/main/java/com/github/retrooper/packetevents/protocol/recipe/data/ShapelessRecipeData.java
> +    private CraftingBookCategory category;
```suggestion
    private final CraftingBookCategory category;
```

2024-02-07 21:27 UTC, NoJokeFNA commented on api/src/main/java/com/github/retrooper/packetevents/protocol/recipe/data/ShapelessRecipeData.java
> +    public CraftingBookCategory getCategory() {
Is the `@Nullable` annotation not needed?

2024-02-07 21:27 UTC, NoJokeFNA commented on api/src/main/java/com/github/retrooper/packetevents/protocol/recipe/data/ShapedRecipeData.java
> +    public ShapedRecipeData(final int width, final int height, final @NotNull String group, final @NotNull CraftingBookCategory category, final @NotNull Ingredient[] ingredients, final ItemStack resu
Is the CraftingBookCategory version-specific? If yes, please make a second constructor

2024-02-07 21:27 UTC, NoJokeFNA commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerUnlockRecipes.java
> +    RecipeBookAction action;
Please add `private final` everywhere

2024-02-07 21:27 UTC, NoJokeFNA commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerUnlockRecipes.java
> +
```suggestion
```

2024-02-07 21:27 UTC, NoJokeFNA commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerUnlockRecipes.java
> +        if(action == RecipeBookAction.INIT) {
```suggestion
        if (action == RecipeBookAction.INIT) {

```

2024-02-07 21:27 UTC, NoJokeFNA commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerUnlockRecipes.java
> +        if(action == RecipeBookAction.INIT) {
```suggestion
        if (action == RecipeBookAction.INIT) {
```

2024-02-08 10:47 UTC, NoJokeFNA commented
Hold up, I just saw the "WrapperPlayServerUnlockRecipes" class. It's definetly not cross-version and a duplicate of #382

2025-01-04 12:02 UTC, BL19 commented
Closing since I don't really have time to fix this and have no use for it anymore. Might open a new PR if I need this again.

2025-01-04 12:02 UTC, closed without merging