1.20.5 update
retrooper/packetevents pull request #658
Opened 2024-01-17 22:13 UTC by booky10

Still WIP, 1.20.5 isn't released yet.

---

Some stuff worth mentioning:
- This introduces mappings for attributes, as new ones were added in 23w51a.
- The `sweeping` enchantment was renamed to `sweeping_edge`, like done in 24w03a.
- The tag field names have been adjusted to be more consistent with the vanilla tag names.

2024-04-23 17:11 UTC, SamB440 commented
Spigot 1.20.5
```
[17:51:32] [Netty Server IO #1/WARN]: Failed to initialize a channel. Closing: [id: 0xfcb31cef, L:/127.0.0.1:25565 - R:/127.0.0.1:54457]
java.lang.IllegalStateException: PacketEvents failed to add a decoder to the netty pipeline. Pipeline handlers: [pe-connection-initializer-packetevents, timeout, legacy_query, splitter, FlowControlHandler#0, pe-decoder-packetevents, decoder, prepender, outbound_config, hackfix, packet_handler, DefaultChannelPipeline$TailContext#0]
        at io.github.retrooper.packetevents.injector.connection.ServerConnectionInitializer.relocateHandlers(ServerConnectionInitializer.java:119) ~[?:?]
        at io.github.retrooper.packetevents.injector.connection.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:73) ~[?:?]
        at io.github.retrooper.packetevents.injector.connection.PreChannelInitializer_v1_12.channelRegistered(PreChannelInitializer_v1_12.java:34) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:176) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:152) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:145) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1383) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:172) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:152) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:815) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:517) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.util.NoSuchElementException: encoder
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.github.retrooper.packetevents.injector.connection.ServerConnectionInitializer.relocateHandlers(ServerConnectionInitializer.java:116) ~[?:?]
        ... 19 more
```

2024-04-24 18:44 UTC, SamB440 requested changes

2024-04-24 18:44 UTC, SamB440 commented on api/src/main/java/com/github/retrooper/packetevents/protocol/attribute/Attributes.java
> +    public static final Attribute GENERIC_GRAVITY = define("generic.scale");
```suggestion
    public static final Attribute GENERIC_GRAVITY = define("generic.gravity");
```

2024-04-24 19:37 UTC, SamB440 commented on api/src/main/java/com/github/retrooper/packetevents/protocol/item/type/ItemTypes.java
> +    public static final ItemType GOLDEN_AXE = builder("golden_axe").setMaxAmount(1).setMaxDurability(32).setAttributes(ItemAttribute.GOLD_TIER, ItemAttribute.AXE).setComponent(DAMAGE, 0).setComponent
Oh this stuff seems a bit cursed with how long it is, I think we should at least make the UUIDS a static constant as they seem to be referenced in the other axes too

2024-04-28 21:46 UTC, retrooper commented
For the next PacketEvents release, we planned to merge both this PR and https://github.com/retrooper/packetevents/pull/648/files#diff-d793ba1bcd8a7285f509a33d48e278d16a8d8318d2189761a09f41bb6fa438a4 
We need to make sure we can fix possible conflicts.

2024-05-01 19:53 UTC, merged

2024-05-01 19:54 UTC, AbhigyaKrishna commented
Thank you for the pr!!