Add WrapperPlayServerWorldEvent
retrooper/packetevents pull request #702
Opened 2024-03-14 05:34 UTC by jtJava

2024-06-24 13:23 UTC, booky10 requested changes

2024-06-24 13:23 UTC, booky10 commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerWorldEvent.java
> +class WrapperPlayServerWorldEvent extends PacketWrapper<WrapperPlayServerWorldEvent> {
should be made public

2024-06-24 13:23 UTC, booky10 commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerWorldEvent.java
> +        }
this seems to be one indention layer too much

2024-06-24 13:23 UTC, booky10 commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerWorldEvent.java
> +class WrapperPlayServerWorldEvent extends PacketWrapper<WrapperPlayServerWorldEvent> {
also renamed to WrapperPlayServerEffect

2024-06-24 13:23 UTC, booky10 commented on api/src/main/java/com/github/retrooper/packetevents/protocol/packettype/PacketType.java
> +            WORLD_EVENT;
this isnt mapped anywhere, the correct name is `EFFECT`

2024-06-24 13:23 UTC, booky10 commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerWorldEvent.java
> +            super(PacketType.Play.Server.WORLD_EVENT);
`EFFECT` instead of `WORLD_EVENT`

2024-06-28 09:33 UTC, retrooper requested changes

2024-06-28 09:33 UTC, retrooper commented on api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerEffect.java
> +    public WrapperPlayServerEffect(PacketReceiveEvent event) {
PacketSendEvent.

2024-06-29 06:13 UTC, jtJava commented
All above issues fixed

2024-09-26 08:35 UTC, booky10 approved these changes

2025-01-27 06:40 UTC, closed without merging