Added: TaskWrapper & Improved FoliaCompatUtil reflections
retrooper/packetevents pull request #709
Opened 2024-04-05 20:04 UTC by Bram1903

Improved the FoliaCompatUtil by making the tasks return a TaskWrapper instead of void, and improved the performance of the util by caching the reflections upon startup, instead of redoing it upon each call. 

The TaskWrapper has wrapper methods that support generic methods supported by both [BukkitTask](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scheduler/BukkitTask.html) & [ScheduledTask](https://jd.papermc.io/paper/1.20/io/papermc/paper/threadedregions/scheduler/ScheduledTask.html) (Paper / Folia). The `ScheduledTask` methods are being invoked through reflections that are being cached upon startup.

2024-04-06 18:08 UTC, Tofaa2 commented
W PR, the old util was horrible

2024-04-17 10:28 UTC, Tofpu requested changes

2024-04-17 10:29 UTC, Bram1903 commented on spigot/src/main/java/io/github/retrooper/packetevents/injector/handlers/PacketEventsDecoder.java
> +                    FoliaCompatUtil.getEntityScheduler().runDelayed(player, (Plugin) PacketEvents.getAPI().getPlugin(), (o) -> player.kickPlayer("PacketEvents 2.0 failed to inject"), null, 1);
Whoops my bad! 😅 Will fix once home!

2024-04-17 19:56 UTC, Bram1903 commented on spigot/src/main/java/io/github/retrooper/packetevents/injector/handlers/PacketEventsDecoder.java
> +                    FoliaCompatUtil.getEntityScheduler().runDelayed(player, (Plugin) PacketEvents.getAPI().getPlugin(), (o) -> player.kickPlayer("PacketEvents 2.0 failed to inject"), null, 1);
Fixed 😄

2024-05-02 21:00 UTC, merged

2024-05-02 21:01 UTC, retrooper commented
Thanks for the PR