Fix recipe packet writing/reading
retrooper/packetevents pull request #799
Opened 2024-05-28 19:20 UTC by booky10

Adds support for 1.19.3+ to the recipe packet:
- Adds categories (cooking + crafting)
- Adds decorated pot crafting recipe support
- Fixes writing of recipe list in 1.20.5+
- Migrates RecipeType to RecipeSerializer using registries
- Fixes order of shaped recipe pattern serialization
- Adds showNotification flag to shaped recipe data

---

Supersedes some parts of #589, but doesn't include an unlock recipe packet wrapper

2024-06-04 08:12 UTC, AbhigyaKrishna commented
Please resolve the conflict with the new build configuration.

2024-06-04 12:26 UTC, booky10 commented
> Please resolve the conflict with the new build configuration.

Done

2024-06-27 14:04 UTC, retrooper requested changes
Some comments crediting MCProtocol could be removed since we rewrote the classes.

2024-06-27 14:04 UTC, retrooper commented on api/src/main/java/com/github/retrooper/packetevents/protocol/recipe/Recipe.java
>  // From MCProtocolLib
Since you rewrote this class it seems, we could remove this comment.

2024-06-27 14:04 UTC, retrooper commented on api/src/main/java/com/github/retrooper/packetevents/protocol/recipe/Ingredient.java
>  // From MCProtocolLib
Arguably the same here, this whole system has been rewritten basically.

2024-06-27 14:53 UTC, retrooper approved these changes

2024-06-27 14:53 UTC, merged

2024-06-27 14:53 UTC, retrooper commented
Thanks for your PR!